version: '3.8'

services:
  authentication:
    build:
      context: ./autentification
    ports:
      - "8081:5001"
    environment:
      - FLASK_ENV=development

  orders:
    build:
      context: ./order
    ports:
      - "8082:5002"
    environment:
      - FLASK_ENV=development

  menu:
    build:
      context: ./menu
    ports:
      - "8083:5003"
    environment:
      - FLASK_ENV=development

  transactions:
    build:
      context: ./finance
    ports:
      - "8084:5004"
    environment:
      - FLASK_ENV=development

  gateway:
    build:
      context: ./gateway
    ports:
      - "80:5000"
    depends_on:
      - authentication
      - orders
      - menu
      - transactions
